---
on:
  push:

jobs:
  ci-terraform:
    # uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@main"
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@tf-scans"
    with:
      enable-cost: false
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
