---
on:
  push:

jobs:
  ci:
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@c92a9055b7fefd0585b45a3a56c0575ece9a4065" # main
    with:
      enable-cost: false
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
