---
on:
  push:

jobs:
  ci:
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@db8156445cc8da73f49cdb019a12060a3e655a40" # v1.0.3
    with:
      enable-cost: false
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
