name: BennieMosher.dev CI for Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.tf'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.tf'

jobs:
  ci-terraform:
    name: Continuous Integration for Terraform
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@main"
    with:
      enable-cost: false
