---
on:
  push:

jobs:
  ci:
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@67edb842805d75055fb204bb2937f076ccce672e" # v1.0.2
    with:
      enable-cost: false
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
