name: Continuous Integration (CI)
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    # uses: ./.github/workflows/lint.yml
    uses: benniemosher-dev/.github/workflows/lint.yml@bam/add-cost-lint-sec-actions

  sec:
    name: Sec
    uses: ./.github/workflows/sec.yml

  cost:
    name: Cost
    uses: ./.github/workflows/cost.yml
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
