---
name: BennieMosher.dev CI for Pre-Commit

on:
  push:

jobs:
  ci-terraform:
    name: Continuous Integration for Pre-Commit
    # uses: "benniemosher-dev/.github/.github/workflows/ci-terraform-pre-commit.yml@main"
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform-pre-commit.yml@tf-scans"
